"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Github, X, Loader2, ExternalLink, Lock, Globe, Eye, EyeOff } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { createRepoAndPushFiles, validateGitHubToken } from "@/app/actions/github"
import type { GeneratedFile } from "@/lib/file-parser"

interface GitHubModalProps {
  isOpen: boolean
  onClose: () => void
  files: GeneratedFile[]
  defaultRepoName: string
  onSuccess?: (repoUrl: string) => void
}

export function GitHubModal({ isOpen, onClose, files, defaultRepoName, onSuccess }: GitHubModalProps) {
  const [token, setToken] = useState("")
  const [showToken, setShowToken] = useState(false)
  const [repoName, setRepoName] = useState(defaultRepoName)
  const [description, setDescription] = useState("Generated by Ralph Builder")
  const [isPrivate, setIsPrivate] = useState(false)
  const [isValidating, setIsValidating] = useState(false)
  const [isPushing, setIsPushing] = useState(false)
  const [username, setUsername] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState<string | null>(null)

  const handleValidateToken = async () => {
    if (!token.trim()) {
      setError("Please enter a GitHub token")
      return
    }

    setIsValidating(true)
    setError(null)

    const result = await validateGitHubToken(token)

    if (result.valid) {
      setUsername(result.username || null)
      setError(null)
    } else {
      setError(result.error || "Invalid token")
      setUsername(null)
    }

    setIsValidating(false)
  }

  const handlePush = async () => {
    if (!token || !username) {
      setError("Please validate your token first")
      return
    }

    if (!repoName.trim()) {
      setError("Please enter a repository name")
      return
    }

    setIsPushing(true)
    setError(null)

    const result = await createRepoAndPushFiles({
      token,
      repoName,
      description,
      isPrivate,
      files,
    })

    if (result.success) {
      setSuccess(result.repoUrl || "Repository created successfully")
      if (result.repoUrl && onSuccess) {
        onSuccess(result.repoUrl)
      }
    } else {
      setError(result.error || "Failed to push to GitHub")
    }

    setIsPushing(false)
  }

  const handleClose = () => {
    setToken("")
    setUsername(null)
    setError(null)
    setSuccess(null)
    onClose()
  }

  if (!isOpen) return null

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center bg-background/80 backdrop-blur-sm"
        onClick={handleClose}
      >
        <motion.div
          initial={{ scale: 0.95, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.95, opacity: 0 }}
          className="w-full max-w-md rounded-xl border border-border bg-card p-6 shadow-xl"
          onClick={(e) => e.stopPropagation()}
        >
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                <Github className="h-5 w-5 text-primary" />
              </div>
              <div>
                <h2 className="text-lg font-semibold">Push to GitHub</h2>
                <p className="text-sm text-muted-foreground">{files.length} files to push</p>
              </div>
            </div>
            <Button variant="ghost" size="icon" onClick={handleClose}>
              <X className="h-4 w-4" />
            </Button>
          </div>

          {success ? (
            <div className="space-y-4">
              <div className="rounded-lg bg-emerald-500/10 border border-emerald-500/20 p-4 text-center">
                <p className="text-emerald-400 font-medium mb-2">Successfully pushed to GitHub!</p>
                <a
                  href={success}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-sm text-primary hover:underline"
                >
                  View Repository <ExternalLink className="h-4 w-4" />
                </a>
              </div>
              <Button onClick={handleClose} className="w-full">
                Done
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="token">Personal Access Token</Label>
                <div className="relative">
                  <Input
                    id="token"
                    type={showToken ? "text" : "password"}
                    placeholder="ghp_xxxxxxxxxxxx"
                    value={token}
                    onChange={(e) => {
                      setToken(e.target.value)
                      setUsername(null)
                      setError(null)
                    }}
                    className="pr-10"
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="absolute right-0 top-0 h-full px-3"
                    onClick={() => setShowToken(!showToken)}
                  >
                    {showToken ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                  </Button>
                </div>
                {username ? (
                  <p className="text-xs text-emerald-400">Authenticated as @{username}</p>
                ) : (
                  <p className="text-xs text-muted-foreground">
                    Need a token?{" "}
                    <a
                      href="https://github.com/settings/tokens/new?scopes=repo&description=Ralph%20Builder"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-primary hover:underline"
                    >
                      Create one here
                    </a>
                  </p>
                )}
              </div>

              {!username && (
                <Button
                  onClick={handleValidateToken}
                  disabled={isValidating || !token.trim()}
                  variant="secondary"
                  className="w-full"
                >
                  {isValidating ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Validating...
                    </>
                  ) : (
                    "Validate Token"
                  )}
                </Button>
              )}

              {username && (
                <>
                  <div className="space-y-2">
                    <Label htmlFor="repoName">Repository Name</Label>
                    <Input
                      id="repoName"
                      value={repoName}
                      onChange={(e) => setRepoName(e.target.value)}
                      placeholder="my-app"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="description">Description</Label>
                    <Input
                      id="description"
                      value={description}
                      onChange={(e) => setDescription(e.target.value)}
                      placeholder="App description"
                    />
                  </div>

                  <div className="flex items-center gap-4">
                    <button
                      type="button"
                      onClick={() => setIsPrivate(false)}
                      className={`flex-1 flex items-center justify-center gap-2 rounded-lg border p-3 transition-colors ${
                        !isPrivate
                          ? "border-primary bg-primary/10 text-primary"
                          : "border-border hover:border-muted-foreground"
                      }`}
                    >
                      <Globe className="h-4 w-4" />
                      <span className="text-sm">Public</span>
                    </button>
                    <button
                      type="button"
                      onClick={() => setIsPrivate(true)}
                      className={`flex-1 flex items-center justify-center gap-2 rounded-lg border p-3 transition-colors ${
                        isPrivate
                          ? "border-primary bg-primary/10 text-primary"
                          : "border-border hover:border-muted-foreground"
                      }`}
                    >
                      <Lock className="h-4 w-4" />
                      <span className="text-sm">Private</span>
                    </button>
                  </div>

                  <Button onClick={handlePush} disabled={isPushing} className="w-full">
                    {isPushing ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Pushing to GitHub...
                      </>
                    ) : (
                      <>
                        <Github className="mr-2 h-4 w-4" />
                        Create & Push
                      </>
                    )}
                  </Button>
                </>
              )}

              {error && <p className="text-sm text-destructive text-center">{error}</p>}
            </div>
          )}
        </motion.div>
      </motion.div>
    </AnimatePresence>
  )
}
