/**
 * ZIP Generator Utility
 * Creates downloadable ZIP files from generated code
 */

import type { GeneratedFile } from "./file-parser"

/**
 * Generate a ZIP file from parsed files using JSZip
 * Returns a Blob that can be downloaded
 */
export async function generateZip(files: GeneratedFile[], projectName = "ralph-app"): Promise<Blob> {
  // Dynamic import of JSZip
  const JSZip = (await import("jszip")).default
  const zip = new JSZip()

  // Create root folder
  const root = zip.folder(projectName)
  if (!root) throw new Error("Failed to create ZIP folder")

  // Add each file to the ZIP
  for (const file of files) {
    root.file(file.path, file.content)
  }

  // Add package.json if not present
  const hasPackageJson = files.some((f) => f.path === "package.json")
  if (!hasPackageJson) {
    root.file("package.json", generatePackageJson(projectName, files))
  }

  // Add README if not present
  const hasReadme = files.some((f) => f.path.toLowerCase().includes("readme"))
  if (!hasReadme) {
    root.file("README.md", generateReadme(projectName, files))
  }

  // Generate the ZIP blob
  return zip.generateAsync({
    type: "blob",
    compression: "DEFLATE",
    compressionOptions: { level: 9 },
  })
}

/**
 * Trigger download of a blob
 */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function generatePackageJson(name: string, files: GeneratedFile[]): string {
  // Detect dependencies from imports
  const allContent = files.map((f) => f.content).join("\n")
  const deps: Record<string, string> = {
    next: "^14.0.0",
    react: "^18.2.0",
    "react-dom": "^18.2.0",
  }
  const devDeps: Record<string, string> = {
    typescript: "^5.0.0",
    "@types/node": "^20.0.0",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    tailwindcss: "^3.4.0",
    postcss: "^8.4.0",
    autoprefixer: "^10.4.0",
  }

  // Check for common dependencies
  if (allContent.includes("framer-motion")) deps["framer-motion"] = "^10.0.0"
  if (allContent.includes("zustand")) deps["zustand"] = "^4.0.0"
  if (allContent.includes("@supabase")) {
    deps["@supabase/supabase-js"] = "^2.0.0"
    deps["@supabase/ssr"] = "^0.1.0"
  }
  if (allContent.includes("stripe")) deps["stripe"] = "^14.0.0"
  if (allContent.includes("lucide-react")) deps["lucide-react"] = "^0.300.0"
  if (allContent.includes("@radix-ui")) deps["@radix-ui/react-slot"] = "^1.0.0"
  if (allContent.includes("class-variance-authority")) deps["class-variance-authority"] = "^0.7.0"
  if (allContent.includes("clsx")) deps["clsx"] = "^2.0.0"
  if (allContent.includes("tailwind-merge")) deps["tailwind-merge"] = "^2.0.0"

  return JSON.stringify(
    {
      name: name.toLowerCase().replace(/\s+/g, "-"),
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: deps,
      devDependencies: devDeps,
    },
    null,
    2,
  )
}

function generateReadme(name: string, files: GeneratedFile[]): string {
  const fileList = files.map((f) => `- \`${f.path}\``).join("\n")

  return `# ${name}

Generated by Ralph Builder - AI-powered app creation.

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Run the development server:
\`\`\`bash
npm run dev
\`\`\`

3. Open [http://localhost:3000](http://localhost:3000) in your browser.

## Project Files

${fileList}

## Deployment

This project is ready to deploy on Vercel:

\`\`\`bash
npx vercel
\`\`\`

---

Built with [Ralph Builder](https://ralphbuilder.com)
`
}
